/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as EntendaRouteImport } from './routes/entenda'
import { Route as EpisodiosRouteImport } from './routes/episodios'
import { Route as FeedExperimentalRouteImport } from './routes/feed-experimental'
import { Route as JurisprudenciaRouteImport } from './routes/jurisprudencia'
import { Route as LeisRouteImport } from './routes/leis'
import { Route as MitosRouteImport } from './routes/mitos'
import { Route as OQuePodeFazerRouteImport } from './routes/o-que-pode-fazer'
import { Route as QuemCompartilhouRouteImport } from './routes/quem-compartilhou'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EpisodiosSlugRouteImport } from './routes/episodios/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntendaRoute = EntendaRouteImport.update({
  id: '/entenda',
  path: '/entenda',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodiosRoute = EpisodiosRouteImport.update({
  id: '/episodios',
  path: '/episodios',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedExperimentalRoute = FeedExperimentalRouteImport.update({
  id: '/feed-experimental',
  path: '/feed-experimental',
  getParentRoute: () => rootRouteImport,
} as any)
const JurisprudenciaRoute = JurisprudenciaRouteImport.update({
  id: '/jurisprudencia',
  path: '/jurisprudencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LeisRoute = LeisRouteImport.update({
  id: '/leis',
  path: '/leis',
  getParentRoute: () => rootRouteImport,
} as any)
const MitosRoute = MitosRouteImport.update({
  id: '/mitos',
  path: '/mitos',
  getParentRoute: () => rootRouteImport,
} as any)
const OQuePodeFazerRoute = OQuePodeFazerRouteImport.update({
  id: '/o-que-pode-fazer',
  path: '/o-que-pode-fazer',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemCompartilhouRoute = QuemCompartilhouRouteImport.update({
  id: '/quem-compartilhou',
  path: '/quem-compartilhou',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodiosSlugRoute = EpisodiosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EpisodiosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/entenda': typeof EntendaRoute
  '/episodios': typeof EpisodiosRouteWithChildren
  '/feed-experimental': typeof FeedExperimentalRoute
  '/jurisprudencia': typeof JurisprudenciaRoute
  '/leis': typeof LeisRoute
  '/mitos': typeof MitosRoute
  '/o-que-pode-fazer': typeof OQuePodeFazerRoute
  '/quem-compartilhou': typeof QuemCompartilhouRoute
  '/sobre': typeof SobreRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/entenda': typeof EntendaRoute
  '/episodios': typeof EpisodiosRouteWithChildren
  '/feed-experimental': typeof FeedExperimentalRoute
  '/jurisprudencia': typeof JurisprudenciaRoute
  '/leis': typeof LeisRoute
  '/mitos': typeof MitosRoute
  '/o-que-pode-fazer': typeof OQuePodeFazerRoute
  '/quem-compartilhou': typeof QuemCompartilhouRoute
  '/sobre': typeof SobreRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/entenda': typeof EntendaRoute
  '/episodios': typeof EpisodiosRouteWithChildren
  '/feed-experimental': typeof FeedExperimentalRoute
  '/jurisprudencia': typeof JurisprudenciaRoute
  '/leis': typeof LeisRoute
  '/mitos': typeof MitosRoute
  '/o-que-pode-fazer': typeof OQuePodeFazerRoute
  '/quem-compartilhou': typeof QuemCompartilhouRoute
  '/sobre': typeof SobreRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conteudos'
    | '/entenda'
    | '/episodios'
    | '/feed-experimental'
    | '/jurisprudencia'
    | '/leis'
    | '/mitos'
    | '/o-que-pode-fazer'
    | '/quem-compartilhou'
    | '/sobre'
    | '/episodios/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conteudos'
    | '/entenda'
    | '/episodios'
    | '/feed-experimental'
    | '/jurisprudencia'
    | '/leis'
    | '/mitos'
    | '/o-que-pode-fazer'
    | '/quem-compartilhou'
    | '/sobre'
    | '/episodios/$slug'
  id:
    | '__root__'
    | '/'
    | '/conteudos'
    | '/entenda'
    | '/episodios'
    | '/feed-experimental'
    | '/jurisprudencia'
    | '/leis'
    | '/mitos'
    | '/o-que-pode-fazer'
    | '/quem-compartilhou'
    | '/sobre'
    | '/episodios/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConteudosRoute: typeof ConteudosRoute
  EntendaRoute: typeof EntendaRoute
  EpisodiosRoute: typeof EpisodiosRouteWithChildren
  FeedExperimentalRoute: typeof FeedExperimentalRoute
  JurisprudenciaRoute: typeof JurisprudenciaRoute
  LeisRoute: typeof LeisRoute
  MitosRoute: typeof MitosRoute
  OQuePodeFazerRoute: typeof OQuePodeFazerRoute
  QuemCompartilhouRoute: typeof QuemCompartilhouRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entenda': {
      id: '/entenda'
      path: '/entenda'
      fullPath: '/entenda'
      preLoaderRoute: typeof EntendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodios': {
      id: '/episodios'
      path: '/episodios'
      fullPath: '/episodios'
      preLoaderRoute: typeof EpisodiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed-experimental': {
      id: '/feed-experimental'
      path: '/feed-experimental'
      fullPath: '/feed-experimental'
      preLoaderRoute: typeof FeedExperimentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurisprudencia': {
      id: '/jurisprudencia'
      path: '/jurisprudencia'
      fullPath: '/jurisprudencia'
      preLoaderRoute: typeof JurisprudenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leis': {
      id: '/leis'
      path: '/leis'
      fullPath: '/leis'
      preLoaderRoute: typeof LeisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitos': {
      id: '/mitos'
      path: '/mitos'
      fullPath: '/mitos'
      preLoaderRoute: typeof MitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-pode-fazer': {
      id: '/o-que-pode-fazer'
      path: '/o-que-pode-fazer'
      fullPath: '/o-que-pode-fazer'
      preLoaderRoute: typeof OQuePodeFazerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-compartilhou': {
      id: '/quem-compartilhou'
      path: '/quem-compartilhou'
      fullPath: '/quem-compartilhou'
      preLoaderRoute: typeof QuemCompartilhouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodios/$slug': {
      id: '/episodios/$slug'
      path: '/$slug'
      fullPath: '/episodios/$slug'
      preLoaderRoute: typeof EpisodiosSlugRouteImport
      parentRoute: typeof EpisodiosRoute
    }
  }
}

interface EpisodiosRouteChildren {
  EpisodiosSlugRoute: typeof EpisodiosSlugRoute
}

const EpisodiosRouteChildren: EpisodiosRouteChildren = {
  EpisodiosSlugRoute: EpisodiosSlugRoute,
}

const EpisodiosRouteWithChildren = EpisodiosRoute._addFileChildren(
  EpisodiosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConteudosRoute: ConteudosRoute,
  EntendaRoute: EntendaRoute,
  EpisodiosRoute: EpisodiosRouteWithChildren,
  FeedExperimentalRoute: FeedExperimentalRoute,
  JurisprudenciaRoute: JurisprudenciaRoute,
  LeisRoute: LeisRoute,
  MitosRoute: MitosRoute,
  OQuePodeFazerRoute: OQuePodeFazerRoute,
  QuemCompartilhouRoute: QuemCompartilhouRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
